# Site information
site_name: Outlines
site_author: The Outlines developers
site_description: >-
    Structured text generation with LLMs

# Repository
repo_name: dottxt-ai/outlines
repo_url: https://github.com/dottxt-ai/outlines

# Copyright
copyright: Copyright &copy; 2023- The Outlines Developers

# Documentation directory
docs_dir: docs_new

# Configuration
theme:
    name: material
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: black
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

    logo: assets/images/logo-square.svg
    favicon: assets/images/logo-simple.png
    icon:
        repo: fontawesome/brands/github
    features:
        - content.code.copy
        - navigation.expand
        - navigation.tabs
        - navigation.sections
        - header.autohide
        - announce.dismiss
    font:
        text: Inter
        code: Source Code Pro

# Additional configuration
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/dottxt-ai
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/remilouf
    generator: false
    analytics:
        provider: google
        property: !ENV GOOGLE_ANALYTICS_KEY
    version:
        provider: mike
        default: latest
        alias: true

# Extensions
markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
          noclasses: True
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.snippets:

extra_css:
    - stylesheets/extra.css

plugins:
    - blog
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      docstring_style: numpy
                      show_submodules: true
    - search
    - section-index
    - social:
          cards_layout_options:
              color: #173a58
    - redirects:
          redirect_maps:
              "welcome.md": "index.md"
              "reference/chat_templating.md": "user_guide/chat_templating.md"
              "blog.md": "https://blog.dottxt.co"
    - git-committers:
        repository: dottxt-ai/outlines
        branch: main
    - git-revision-date-localized:
        enable_creation_date: true
        type: timeago

nav:
    - Home:
          - index.md
          - User Guide: user_guide/index.md
          - API Reference: reference/index.md
          - Examples: cookbook/index.md
    - Guide:
          - Introduction:
                - Get started: getting_started/index.md
                - Installation: installation.md
                - Licence: licence.md
          - User Guide:
                - The Basics: user_guide/index.md
                - Selecting an Inference Engine: user_guide/selecting_an_inference_backend.md
                - Unstructured Text Generation: user_guide/unstructured.md
                - Structured Generation: user_guide/structured_generation/index.md
                - Chat Templating for Instruct Models: user_guide/chat_templating.md
                - Generation Formats:
                      - JSON: user_guide/structured_generation/json.md
                      - Regular expressions: user_guide/structured_generation/regex.md
                      - Context-free grammars: user_guide/structured_generation/cfg.md
                      - Multiple choice: user_guide/structured_generation/multiple_choice.md
                - Prompting:
                      - Applications: user_guide/prompting/applications.md
                      - Templates: user_guide/prompting/templates.md
                - Easy Regular Expressions: user_guide/regex_dsl.md
                - Migrating to v1: user_guide/migration.md
    - API Reference:
          - Overview: reference/index.md
          - Format types:
                - Overview: reference/types/index.md
                - JSON: reference/types/json_schema.md
                - Regex: reference/types/regex.md
                - Context-free grammars: reference/types/cfg.md

          - Core:
                - Generator: reference/core/generator.md

          - Supported Models:
                - Anthropic: reference/models/anthropic.md
                - Dottxt: reference/models/dottxt.md
                - Gemini: reference/models/gemini.md
                - Llamacpp: reference/models/llamacpp.md
                - Mlx-lm: reference/models/mlxlm.md
                - Ollama: reference/models/ollama.md
                - OpenAI: reference/models/openai.md
                - SgLang: reference/models/sglang.md
                - TGI: reference/models/tgi.md
                - Transformers: reference/models/transformers.md
                - vLLM (online server): reference/models/vllm.md
                - vLLM (offline): reference/models/vllm_offline.md

          - Utilities:
                - Applications: reference/utility/application.md
                - Template: reference/utility/template.md

          - Advanced:
                - Guide: reference/advanced/guide.md
                - Parsing: reference/advanced/parsing.md
    - Examples:
          - cookbook/index.md
          - Classification: cookbook/classification.md
          - Named Entity Extraction: cookbook/extraction.md
          - Generate synthetic data: cookbook/dating_profiles.md
          - Summarize a document: cookbook/chain_of_density.md
          - Playing chess: cookbook/models_playing_chess.md
          - Perspective-taking prompting: cookbook/simtom.md
          - Question-answering with citations: cookbook/qa-with-citations.md
          - Knowledge Graph Extraction: cookbook/knowledge_graph_extraction.md
          - Structured Generation Workflow: cookbook/structured_generation_workflow.md
          - Chain of Thought (CoT): cookbook/chain_of_thought.md
          - ReAct Agent: cookbook/react_agent.md
          - Vision-Language Models: cookbook/atomic_caption.md
          - Structured Generation from PDFs: cookbook/read-pdfs.md
          - Earnings reports to CSV: cookbook/earnings-reports.md
          - Digitizing receipts with vision models: cookbook/receipt-digitization.md
          - Extract events details from text: cookbook/extract_event_details.md
          - Run on the cloud:
                - BentoML: cookbook/deploy-using-bentoml.md
                - Cerebrium: cookbook/deploy-using-cerebrium.md
                - Modal: cookbook/deploy-using-modal.md
    - Community:
        - community/index.md
        - Feedback 🫶: community/feedback.md
        - Our Discord Server ☕: https://discord.com/invite/R9DSu34mGd
        - How to Contribute 🏗️: community/contribute.md
        - Community Projects 👏: community/examples.md
        - Versioning Guide 📌: community/versioning.md

    - Blog: https://blog.dottxt.co
