contact_links:
  - name: 🤔 Questions & Help
    url: https://github.com/outlines-dev/outlines/discussions/new
    about: "If you have a question about how to use Outlines, please start a discussion."
