"""Integration with LiteLLM's unified API gateway."""

from typing import (
    TYPE_CHECKING,
    Any,
    AsyncIterator,
    Iterator,
    Optional,
    Union,
)

from pydantic import BaseModel

from outlines.models.base import AsyncModel, Model
from outlines.models.openai import OpenAITypeAdapter

if TYPE_CHECKING:
    pass

__all__ = ["AsyncLiteLLM", "LiteLLM", "from_litellm"]


class LiteLLMTypeAdapter(OpenAITypeAdapter):
    """Type adapter for the `LiteLLM` model.

    LiteLLM uses the same message and response format as OpenAI, so this
    adapter inherits from `OpenAITypeAdapter` directly.

    """

    pass


class LiteLLM(Model):
    """Thin wrapper around the `litellm` library.

    LiteLLM provides a unified interface to 100+ LLM providers (OpenAI,
    Anthropic, Google, Cohere, Mistral, Bedrock, Azure, Ollama, and more)
    through a single `completion()` call.

    See https://docs.litellm.ai/docs/providers for supported providers
    and model name formats.

    """

    def __init__(
        self,
        model_name: str,
        **kwargs: Any,
    ):
        """
        Parameters
        ----------
        model_name
            The model identifier in LiteLLM format (e.g. ``"gpt-4o"``,
            ``"anthropic/claude-3-sonnet"``, ``"gemini/gemini-pro"``).
        **kwargs
            Additional keyword arguments passed to ``litellm.completion()``
            on every call (e.g. ``api_key``, ``api_base``, ``timeout``).

        """
        self.model_name = model_name
        self.kwargs = kwargs
        self.type_adapter = LiteLLMTypeAdapter()

    def generate(
        self,
        model_input: Union[str, list],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs: Any,
    ) -> Union[str, list[str]]:
        """Generate text using LiteLLM.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to ``litellm.completion()``.

        Returns
        -------
        Union[str, list[str]]
            The text generated by the model.

        """
        import litellm

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        merged_kwargs = {**self.kwargs, **inference_kwargs}

        result = litellm.completion(
            model=self.model_name,
            messages=messages,
            **response_format,
            **merged_kwargs,
        )

        contents = [
            choice.message.content for choice in result.choices
        ]

        if len(contents) == 1:
            return contents[0]
        else:
            return contents

    def generate_batch(
        self,
        model_input,
        output_type=None,
        **inference_kwargs,
    ):
        raise NotImplementedError(
            "LiteLLM does not support batch inference."
        )

    def generate_stream(
        self,
        model_input: Union[str, list],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs,
    ) -> Iterator[str]:
        """Stream text using LiteLLM.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to ``litellm.completion()``.

        Returns
        -------
        Iterator[str]
            An iterator that yields the text generated by the model.

        """
        import litellm

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        merged_kwargs = {**self.kwargs, **inference_kwargs}

        stream = litellm.completion(
            model=self.model_name,
            messages=messages,
            stream=True,
            **response_format,
            **merged_kwargs,
        )

        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content is not None:
                yield chunk.choices[0].delta.content


class AsyncLiteLLM(AsyncModel):
    """Async wrapper around the `litellm` library.

    See `LiteLLM` for details on supported providers and model formats.

    """

    def __init__(
        self,
        model_name: str,
        **kwargs: Any,
    ):
        """
        Parameters
        ----------
        model_name
            The model identifier in LiteLLM format.
        **kwargs
            Additional keyword arguments passed to ``litellm.acompletion()``
            on every call.

        """
        self.model_name = model_name
        self.kwargs = kwargs
        self.type_adapter = LiteLLMTypeAdapter()

    async def generate(
        self,
        model_input: Union[str, list],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs: Any,
    ) -> Union[str, list[str]]:
        """Generate text using LiteLLM asynchronously.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to ``litellm.acompletion()``.

        Returns
        -------
        Union[str, list[str]]
            The text generated by the model.

        """
        import litellm

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        merged_kwargs = {**self.kwargs, **inference_kwargs}

        result = await litellm.acompletion(
            model=self.model_name,
            messages=messages,
            **response_format,
            **merged_kwargs,
        )

        contents = [
            choice.message.content for choice in result.choices
        ]

        if len(contents) == 1:
            return contents[0]
        else:
            return contents

    async def generate_batch(
        self,
        model_input,
        output_type=None,
        **inference_kwargs,
    ):
        raise NotImplementedError(
            "LiteLLM does not support batch inference."
        )

    async def generate_stream(  # type: ignore
        self,
        model_input: Union[str, list],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs,
    ) -> AsyncIterator[str]:
        """Stream text using LiteLLM asynchronously.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to ``litellm.acompletion()``.

        Returns
        -------
        AsyncIterator[str]
            An async iterator that yields the text generated by the model.

        """
        import litellm

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        merged_kwargs = {**self.kwargs, **inference_kwargs}

        stream = await litellm.acompletion(
            model=self.model_name,
            messages=messages,
            stream=True,
            **response_format,
            **merged_kwargs,
        )

        async for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content is not None:
                yield chunk.choices[0].delta.content


def from_litellm(
    model_name: str,
    async_client: bool = False,
    **kwargs: Any,
) -> Union[LiteLLM, AsyncLiteLLM]:
    """Create an Outlines `LiteLLM` or `AsyncLiteLLM` model instance.

    LiteLLM provides a unified interface to 100+ LLM providers. See
    https://docs.litellm.ai/docs/providers for supported providers
    and model name formats.

    Parameters
    ----------
    model_name
        The model identifier in LiteLLM format (e.g. ``"gpt-4o"``,
        ``"anthropic/claude-3-sonnet"``, ``"gemini/gemini-pro"``).
    async_client
        If ``True``, return an ``AsyncLiteLLM`` instance for use with
        ``async``/``await``.
    **kwargs
        Additional keyword arguments passed to ``litellm.completion()``
        or ``litellm.acompletion()`` on every call (e.g. ``api_key``,
        ``api_base``, ``timeout``).

    Returns
    -------
    Union[LiteLLM, AsyncLiteLLM]
        An Outlines `LiteLLM` or `AsyncLiteLLM` model instance.

    """
    if async_client:
        return AsyncLiteLLM(model_name, **kwargs)
    return LiteLLM(model_name, **kwargs)
