"""Integration with MiniMax's API.

MiniMax provides an OpenAI-compatible API at ``https://api.minimax.io/v1``.
This module wraps the ``openai`` Python SDK, pointing it at the MiniMax
endpoint, and adds MiniMax-specific behaviour:

* **Temperature clamping** – the API requires temperature to be in the
  open-closed interval (0.0, 1.0].
* **Thinking-tag stripping** – MiniMax M2.5 models may include
  ``<think>…</think>`` reasoning traces in their output.  These are
  automatically removed before returning the generated text.
* **JSON-object mode** – MiniMax supports ``response_format``
  ``json_object`` but not OpenAI's strict ``json_schema`` mode.
  ``MiniMaxTypeAdapter`` transparently falls back to ``json_object``
  when a JSON schema is requested.

Available models include ``MiniMax-M2.5`` and ``MiniMax-M2.5-highspeed``,
both supporting a 204K context window.
"""

import re
from typing import (
    TYPE_CHECKING,
    Any,
    AsyncIterator,
    Iterator,
    Optional,
    Union,
    cast,
)

from pydantic import BaseModel

from outlines.inputs import Chat
from outlines.models.base import AsyncModel, Model
from outlines.models.openai import OpenAITypeAdapter
from outlines.types import CFG, JsonSchema, Regex
from outlines.types.utils import is_native_dict

if TYPE_CHECKING:
    from openai import AsyncOpenAI as AsyncOpenAIClient, OpenAI as OpenAIClient

__all__ = ["AsyncMiniMax", "MiniMax", "from_minimax"]

MINIMAX_BASE_URL = "https://api.minimax.io/v1"

_THINK_RE = re.compile(r"<think>.*?</think>\s*", re.DOTALL)
_CODE_BLOCK_RE = re.compile(r"```(?:json)?\s*\n?(.*?)\n?\s*```", re.DOTALL)


def _clamp_temperature(kwargs: dict) -> dict:
    """Ensure *temperature* is in the range (0.0, 1.0].

    MiniMax rejects ``temperature=0`` and values above 1.0.  This helper
    silently clamps the value so that callers do not have to remember the
    constraint.
    """
    if "temperature" in kwargs:
        t = kwargs["temperature"]
        if t <= 0:
            kwargs["temperature"] = 0.01
        elif t > 1.0:
            kwargs["temperature"] = 1.0
    return kwargs


def _strip_thinking(text: str) -> str:
    """Remove ``<think>…</think>`` blocks and markdown code fences."""
    text = _THINK_RE.sub("", text).strip()
    # Strip markdown code blocks (```json … ```)
    match = _CODE_BLOCK_RE.search(text)
    if match:
        text = match.group(1).strip()
    return text


class MiniMaxTypeAdapter(OpenAITypeAdapter):
    """Type adapter for MiniMax models.

    Inherits the OpenAI message formatting but overrides
    ``format_json_output_type`` to use ``json_object`` mode instead of
    the strict ``json_schema`` mode that MiniMax does not support.
    """

    def format_output_type(self, output_type: Optional[Any] = None) -> dict:
        if isinstance(output_type, Regex):
            raise TypeError(
                "Regex-based structured outputs are not available with "
                "MiniMax. Use an open source model or dottxt instead."
            )
        elif isinstance(output_type, CFG):
            raise TypeError(
                "CFG-based structured outputs are not available with "
                "MiniMax. Use an open source model or dottxt instead."
            )

        if output_type is None:
            return {}
        elif is_native_dict(output_type):
            return self.format_json_mode_type()
        elif JsonSchema.is_json_schema(output_type):
            # MiniMax does not support strict json_schema mode; fall back
            # to json_object mode which still constrains output to JSON.
            return self.format_json_mode_type()
        else:
            type_name = getattr(output_type, "__name__", output_type)
            raise TypeError(
                f"The type `{type_name}` is not available with MiniMax. "
                "Use an open source model or dottxt instead."
            )


class MiniMax(Model):
    """Thin wrapper around the ``openai.OpenAI`` client configured for MiniMax.

    This wrapper re-uses the OpenAI message format (via
    :class:`OpenAITypeAdapter`) and adds MiniMax-specific temperature
    clamping.
    """

    def __init__(
        self,
        client: "OpenAIClient",
        model_name: Optional[str] = None,
    ):
        self.client = client
        self.model_name = model_name
        self.type_adapter = MiniMaxTypeAdapter()

    def generate(
        self,
        model_input: Union[Chat, list, str],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs: Any,
    ) -> Union[str, list[str]]:
        """Generate text using MiniMax.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to the client.

        Returns
        -------
        Union[str, list[str]]
            The text generated by the model.

        """
        import openai

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        if "model" not in inference_kwargs and self.model_name is not None:
            inference_kwargs["model"] = self.model_name

        inference_kwargs = _clamp_temperature(inference_kwargs)

        try:
            result = self.client.chat.completions.create(
                messages=messages,
                **response_format,
                **inference_kwargs,
            )
        except openai.BadRequestError as e:
            if e.body and isinstance(e.body, dict) and e.body.get("message", "").startswith("Invalid schema"):
                raise TypeError(
                    f"MiniMax does not support your schema: {e.body['message']}. "
                    "Try a local model or dottxt instead."
                )
            else:
                raise e

        result_messages = [choice.message for choice in result.choices]
        for message in result_messages:
            if getattr(message, "refusal", None) is not None:
                raise ValueError(
                    f"MiniMax refused to answer the request: {message.refusal}"
                )

        if len(result_messages) == 1:
            return _strip_thinking(result_messages[0].content)
        else:
            return [_strip_thinking(m.content) for m in result_messages]

    def generate_batch(
        self,
        model_input,
        output_type=None,
        **inference_kwargs,
    ):
        raise NotImplementedError(
            "Batch inference is not supported with MiniMax."
        )

    def generate_stream(
        self,
        model_input: Union[Chat, list, str],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs: Any,
    ) -> Iterator[str]:
        """Stream text using MiniMax.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to the client.

        Returns
        -------
        Iterator[str]
            An iterator that yields the text generated by the model.

        """
        import openai

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        if "model" not in inference_kwargs and self.model_name is not None:
            inference_kwargs["model"] = self.model_name

        inference_kwargs = _clamp_temperature(inference_kwargs)

        try:
            stream = self.client.chat.completions.create(
                stream=True,
                messages=messages,
                **response_format,
                **inference_kwargs,
            )
        except openai.BadRequestError as e:
            if e.body and isinstance(e.body, dict) and e.body.get("message", "").startswith("Invalid schema"):
                raise TypeError(
                    f"MiniMax does not support your schema: {e.body['message']}. "
                    "Try a local model or dottxt instead."
                )
            else:
                raise e

        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content is not None:
                yield chunk.choices[0].delta.content


class AsyncMiniMax(AsyncModel):
    """Thin wrapper around ``openai.AsyncOpenAI`` configured for MiniMax.

    This wrapper re-uses the OpenAI message format (via
    :class:`MiniMaxTypeAdapter`) and adds MiniMax-specific temperature
    clamping and thinking-tag stripping.
    """

    def __init__(
        self,
        client: "AsyncOpenAIClient",
        model_name: Optional[str] = None,
    ):
        self.client = client
        self.model_name = model_name
        self.type_adapter = MiniMaxTypeAdapter()

    async def generate(
        self,
        model_input: Union[Chat, list, str],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs: Any,
    ) -> Union[str, list[str]]:
        """Generate text using MiniMax asynchronously.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to the client.

        Returns
        -------
        Union[str, list[str]]
            The text generated by the model.

        """
        import openai

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        if "model" not in inference_kwargs and self.model_name is not None:
            inference_kwargs["model"] = self.model_name

        inference_kwargs = _clamp_temperature(inference_kwargs)

        try:
            result = await self.client.chat.completions.create(
                messages=messages,
                **response_format,
                **inference_kwargs,
            )
        except openai.BadRequestError as e:
            if e.body and isinstance(e.body, dict) and e.body.get("message", "").startswith("Invalid schema"):
                raise TypeError(
                    f"MiniMax does not support your schema: {e.body['message']}. "
                    "Try a local model or dottxt instead."
                )
            else:
                raise e

        result_messages = [choice.message for choice in result.choices]
        for message in result_messages:
            if getattr(message, "refusal", None) is not None:
                raise ValueError(
                    f"MiniMax refused to answer the request: {message.refusal}"
                )

        if len(result_messages) == 1:
            return _strip_thinking(result_messages[0].content)
        else:
            return [_strip_thinking(m.content) for m in result_messages]

    async def generate_batch(
        self,
        model_input,
        output_type=None,
        **inference_kwargs,
    ):
        raise NotImplementedError(
            "Batch inference is not supported with MiniMax."
        )

    async def generate_stream(  # type: ignore
        self,
        model_input: Union[Chat, list, str],
        output_type: Optional[Union[type[BaseModel], str]] = None,
        **inference_kwargs: Any,
    ) -> AsyncIterator[str]:
        """Stream text using MiniMax asynchronously.

        Parameters
        ----------
        model_input
            The prompt based on which the model will generate a response.
        output_type
            The desired format of the response generated by the model.
        **inference_kwargs
            Additional keyword arguments to pass to the client.

        Returns
        -------
        AsyncIterator[str]
            An async iterator that yields the text generated by the model.

        """
        import openai

        messages = self.type_adapter.format_input(model_input)
        response_format = self.type_adapter.format_output_type(output_type)

        if "model" not in inference_kwargs and self.model_name is not None:
            inference_kwargs["model"] = self.model_name

        inference_kwargs = _clamp_temperature(inference_kwargs)

        try:
            stream = await self.client.chat.completions.create(
                stream=True,
                messages=messages,
                **response_format,
                **inference_kwargs,
            )
        except openai.BadRequestError as e:
            if e.body and isinstance(e.body, dict) and e.body.get("message", "").startswith("Invalid schema"):
                raise TypeError(
                    f"MiniMax does not support your schema: {e.body['message']}. "
                    "Try a local model or dottxt instead."
                )
            else:
                raise e

        async for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content is not None:
                yield chunk.choices[0].delta.content


def from_minimax(
    client: Union["OpenAIClient", "AsyncOpenAIClient"],
    model_name: Optional[str] = None,
) -> Union[MiniMax, AsyncMiniMax]:
    """Create an Outlines ``MiniMax`` model from an ``openai`` client.

    If you do not already have a client, the easiest way to get started is::

        import openai
        import outlines

        client = openai.OpenAI(
            api_key="YOUR_MINIMAX_API_KEY",
            base_url="https://api.minimax.io/v1",
        )
        model = outlines.from_minimax(client, "MiniMax-M2.5")

    Parameters
    ----------
    client
        An ``openai.OpenAI`` or ``openai.AsyncOpenAI`` instance whose
        ``base_url`` is set to the MiniMax endpoint.
    model_name
        The MiniMax model to use, e.g. ``"MiniMax-M2.5"`` or
        ``"MiniMax-M2.5-highspeed"``.

    Returns
    -------
    Union[MiniMax, AsyncMiniMax]
        An Outlines ``MiniMax`` or ``AsyncMiniMax`` model instance.

    """
    import openai

    if isinstance(client, openai.AsyncOpenAI):
        return AsyncMiniMax(client, model_name)
    elif isinstance(client, openai.OpenAI):
        return MiniMax(client, model_name)
    else:
        raise ValueError(
            "Invalid client type. The client must be an instance of "
            "`openai.OpenAI` or `openai.AsyncOpenAI`."
        )
